// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Match struct {
	ID        uuid.UUID `json:"id"`
	Player1   string    `json:"player_1"`
	Player2   string    `json:"player_2"`
	CreatedAt time.Time `json:"created_at"`
}

type Score struct {
	MatchID     uuid.UUID `json:"match_id"`
	GameID      uuid.UUID `json:"game_id"`
	Winner      string    `json:"winner"`
	WinnerScore int16     `json:"winner_score"`
	LoserScore  int16     `json:"loser_score"`
	CreatedAt   time.Time `json:"created_at"`
	PlayedAt    time.Time `json:"played_at"`
}
