app = "robswebhub"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENVIRONMENT = "production"
  APP_APPLICATION__PORT = "8080"
  APP_APPLICATION__HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "5s"
    interval = "15s"
    method = "HEAD"
    path = "/"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    [http_service.checks.headers]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
